name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v

    - name: Build Documentation
      run: |
        swift package --allow-writing-to-directory ./docs \
          generate-documentation --target NestedA11yIDs \
          --disable-indexing \
          --transform-for-static-hosting \
          --hosting-base-path NestedA11yIDs \
          --output-path ./docs

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ./docs
